# Generated by Django 4.2.20 on 2025-04-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sinf nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars nomi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='maktab.grade', verbose_name='Sinf')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Darslik nomi')),
                ('pdf_file', models.FileField(upload_to='textbooks/', verbose_name='PDF fayl')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='textbooks/covers/', verbose_name='Muqova rasmi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='maktab.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Darslik',
                'verbose_name_plural': 'Darsliklar',
            },
        ),
        migrations.CreateModel(
            name='TextbookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Sahifa raqami')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_pages', to='maktab.lesson', verbose_name='Dars')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='maktab.textbook', verbose_name='Darslik')),
            ],
            options={
                'verbose_name': 'Darslik sahifasi',
                'verbose_name_plural': 'Darslik sahifalari',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Qism nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='maktab.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Metodika nomi')),
                ('content', models.TextField(verbose_name='Metodika mazmuni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='methodologies/images/', verbose_name='Rasm')),
                ('file', models.FileField(blank=True, null=True, upload_to='methodologies/files/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='maktab.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Metodika',
                'verbose_name_plural': 'Metodikalar',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='maktab.section', verbose_name='Qism'),
        ),
    ]
