# Generated by Django 5.2.4 on 2025-07-21 15:44

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sinf nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars nomi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Qism nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name="Tug'ilgan joy")),
                ('role', models.CharField(choices=[('teacher', "O'qituvchi"), ('parent', 'Ota-ona')], max_length=10, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name="So'nggi kirgan vaqt")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Metodika nomi')),
                ('content', models.TextField(verbose_name='Metodika mazmuni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='methodologies/images/', verbose_name='Rasm')),
                ('file', models.FileField(blank=True, null=True, upload_to='methodologies/files/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Havola')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='maktab.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Metodika',
                'verbose_name_plural': 'Metodikalar',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='maktab.section', verbose_name='Qism'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='maktab.grade', verbose_name='Sinf')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='maktab.subject', verbose_name='Fan'),
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Darslik nomi')),
                ('pdf_file', models.FileField(upload_to='textbooks/', verbose_name='PDF fayl')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='textbooks/covers/', verbose_name='Muqova rasmi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='maktab.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Darslik',
                'verbose_name_plural': 'Darsliklar',
            },
        ),
        migrations.CreateModel(
            name='TextbookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Sahifa raqami')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_pages', to='maktab.lesson', verbose_name='Dars')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='maktab.textbook', verbose_name='Darslik')),
            ],
            options={
                'verbose_name': 'Darslik sahifasi',
                'verbose_name_plural': 'Darslik sahifalari',
            },
        ),
    ]
