# Generated by Django 4.2.20 on 2025-05-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodology',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Havola'),
        ),
    ]
