# Generated by Django 5.2.4 on 2025-07-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', "O'qituvchi"), ('parent', 'Ota-ona')], max_length=10, null=True, verbose_name='Rol'),
        ),
    ]
