# Generated by Django 5.2.4 on 2025-07-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Sahifa mazmuni'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vazifa nomi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', 'Orta'), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik darajasi')),
                ('description', models.TextField(verbose_name='Vazifa tavsifi')),
                ('instructions', models.TextField(verbose_name="Bajarish yo'riqnomasi")),
                ('time_estimate', models.PositiveIntegerField(default=30, verbose_name='Bajarish vaqti (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maktab.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['lesson__order', 'title'],
            },
        ),
    ]
