# Generated by Django 5.2.4 on 2025-07-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0004_alter_textbookpage_description_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='maktab.section', verbose_name='Qism'),
            preserve_default=False,
        ),
    ]
