# Generated by Django 5.2.4 on 2025-07-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0005_textbook_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='maktab.grade', verbose_name='Sinf'),
            preserve_default=False,
        ),
    ]
